on:
  repository_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Send User Email of Credentials
        env:
          KEY: ${{ github.event.client_payload.key }}
          FIRSTNAME: ${{ github.event.client_payload.firstname }}
          LASTNAME: ${{ github.event.client_payload.lastname }}
          JOBTITLE: ${{ github.event.client_payload.title }}
          REPORTER: ${{ github.event.client_payload.reporter }}
        run: |
          CLIENT_ID=${{ vars.CLIENT_ID }}
          CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}
          SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }}
          MAIL_PAYLOAD_FILE="/tmp/mailpayload"
          
          TOKEN=$(curl -X POST \
          -H "Host: login.microsoftonline.com" \
          -H "Content-type: application/x-www-form-urlencoded" \
          https://login.microsoftonline.com/0496c0c5-5b34-4de0-a252-686f82ec384f/oauth2/v2.0/token \
          -d "client_id=$CLIENT_ID&scope=https%3A%2F%2Fgraph.microsoft.com%2F.default&client_secret=$CLIENT_SECRET&grant_type=client_credentials" \
          | jq -r .access_token)

          echo "Got the token"

          USER=$(echo "$FIRSTNAME.$LASTNAME@kencamarador.com" | tr '[:upper:]' '[:lower:]')
          PASSWORD=$(openssl rand -base64 12 | tr -dc 'a-zA-Z0-9!@#$%^&*()-_+=')

          echo $USER
          echo $REPORTER


          curl -X PATCH -H "Authorization: Bearer $TOKEN" -H "Content-type: application/json" \
          -d '{
            "accountEnabled": true
            }
          }' \
          https://graph.microsoft.com/v1.0/users/$USER


          curl -X PATCH -H "Authorization: Bearer $TOKEN" -H "Content-type: application/json" \
          -d '{
            "passwordProfile": {
              "forceChangePasswordNextSignIn": true,
              "password": "'"$PASSWORD"'"
            }
          }' \
          https://graph.microsoft.com/v1.0/users/$USER


            curl -X POST --url https://api.sendgrid.com/v3/mail/send \
            -H "Authorization: Bearer $SENDGRID_API_KEY" \
            -H "Content-Type: application/json" \
            --data '{
              "personalizations": [{
                "to": [{
                  "email": "$REPORTER",
                  "name": "John Doe"
                }],
                "subject": "Your Work Credentials"
              }],
              "content": [{
                "type": "text/html",
                "value": "<body style=\"font-family:Arial,sans-serif;margin:0;padding:0;\">
                          <div style=\"max-width:600px;margin:10px 20px 0;padding:20px;border:1px solid #ccc;border-radius:5px;\">
                              <div style=\"border-bottom:1px solid #ccc;padding-bottom:10px;display:flex;align-items:center;\">
                                  <h2 style=\"color:#46369C;margin:0;font-weight:normal;\">Your Credentials</h2>
                                  <span style=\"color:#888;font-size:16px;vertical-align:middle;margin-left:10px;border-left:1px solid #888;height:20px;\"></span>
                                  <span style=\"color:#888;font-size:20px;margin-left:10px;\">Arteria AI</span>
                              </div>
                            Hi $FIRSTNAME,

                            Welcome to the Team! Below you will find your temporary login credentials to access your Arteria AI account. You will be prompted to setup Multi Factor Authentication, so please ensure you have your mobile phone near you. 
                                        <div style=\"border: 1px solid #ccc; background-color: #EAE8F7; padding: 0 10px; border-radius: 5px;\">
                                            <p><strong>Email:</strong>$FIRSTNAME.$LASTNAME@kencamarador.com</p>
                                            <p><strong>Password:</strong>$PASSWORD</p>
                                        </div>
                            <p>If you are having issues with your account, please inform your manager.</p>
                            Regards,
                            Service Desk
                                    </div>

                                </div>
                            </body>"
              }],
              "from": {
                "email": "admin@kencamarador.com",
                "name": "Service Desk"
              },
              "reply_to": {
                "email": "admin@kencamarador.com",
                "name": "Service Desk"
              }
            }'



