on:
  repository_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Send User Email of Credentials
        env:
          KEY: ${{ github.event.client_payload.key }}
          FIRSTNAME: ${{ github.event.client_payload.firstname }}
          LASTNAME: ${{ github.event.client_payload.lastname }}
          JOBTITLE: ${{ github.event.client_payload.title }}
          REPORTER: ${{ github.event.client_payload.reporter }}
        run: |
          CLIENT_ID=${{ vars.CLIENT_ID }}
          CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}
          SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }}
          MAIL_PAYLOAD_FILE="/tmp/mailpayload"
          
          TOKEN=$(curl -X POST \
          -H "Host: login.microsoftonline.com" \
          -H "Content-type: application/x-www-form-urlencoded" \
          https://login.microsoftonline.com/0496c0c5-5b34-4de0-a252-686f82ec384f/oauth2/v2.0/token \
          -d "client_id=$CLIENT_ID&scope=https%3A%2F%2Fgraph.microsoft.com%2F.default&client_secret=$CLIENT_SECRET&grant_type=client_credentials" \
          | jq -r .access_token)

          echo "Got the token"

          USER=$(echo "$FIRSTNAME.$LASTNAME@kencamarador.com" | tr '[:upper:]' '[:lower:]')
          PASSWORD=$(openssl rand -base64 12 | tr -dc 'a-zA-Z0-9!@#$%^&*()-_+=')

          echo $USER
          echo $REPORTER


          curl -X PATCH -H "Authorization: Bearer $TOKEN" -H "Content-type: application/json" \
          -d '{
            "accountEnabled": true
            }
          }' \
          https://graph.microsoft.com/v1.0/users/$USER


          curl -X PATCH -H "Authorization: Bearer $TOKEN" -H "Content-type: application/json" \
          -d '{
            "passwordProfile": {
              "forceChangePasswordNextSignIn": true,
              "password": "'"$PASSWORD"'"
            }
          }' \
          https://graph.microsoft.com/v1.0/users/$USER


          curl -X POST --url https://api.sendgrid.com/v3/mail/send \
          -H "Authorization: Bearer $SENDGRID_API_KEY" \
          -H "Content-Type: application/json" \
          --data '{
          "from":{
                "email":"admin@kencamarador.com"
            },
            "personalizations":[
                {
                  "to":[
                      {
                        "email":"admin@kencamarador.com"
                      }
                  ],
                  "dynamic_template_data":{
                      "FIRSTNAME": "'"$FIRSTNAME"'",
                      "LASTNAME": "'"$LASTNAME"'",
                      "EMAIL":"'"$USER"'"
                      "PASSWORD": "'"$PASSWORD"'"
                    }
                }
            ],
            "template_id":"d-562a4a3c57b14e03a924d084c0d066dc"
          }'

