on:
  repository_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Send User Email of Credentials
        env:
          KEY: ${{ github.event.client_payload.key }}
          FIRSTNAME: ${{ github.event.client_payload.firstname }}
          LASTNAME: ${{ github.event.client_payload.lastname }}
          JOBTITLE: ${{ github.event.client_payload.title }}
          REPORTER: ${{ github.event.client_payload.reporter }}
        run: |
          CLIENT_ID=${{ vars.CLIENT_ID }}
          CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}
          SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }}
          MAIL_PAYLOAD_FILE="/tmp/mailpayload"
          
          TOKEN=$(curl -X POST \
          -H "Host: login.microsoftonline.com" \
          -H "Content-type: application/x-www-form-urlencoded" \
          https://login.microsoftonline.com/0496c0c5-5b34-4de0-a252-686f82ec384f/oauth2/v2.0/token \
          -d "client_id=$CLIENT_ID&scope=https%3A%2F%2Fgraph.microsoft.com%2F.default&client_secret=$CLIENT_SECRET&grant_type=client_credentials" \
          | jq -r .access_token)

          echo "Got the token"

          USER=$(echo "$FIRSTNAME.$LASTNAME@kencamarador.com" | tr '[:upper:]' '[:lower:]')
          PASSWORD=$(openssl rand -base64 12 | tr -dc 'a-zA-Z0-9!@#$%^&*()-_+=')

          echo $USER
          echo $REPORTER


          curl -X PATCH -H "Authorization: Bearer $TOKEN" -H "Content-type: application/json" \
          -d '{
            "accountEnabled": true
            }
          }' \
          https://graph.microsoft.com/v1.0/users/$USER


          curl -X PATCH -H "Authorization: Bearer $TOKEN" -H "Content-type: application/json" \
          -d '{
            "passwordProfile": {
              "forceChangePasswordNextSignIn": true,
              "password": "'"$PASSWORD"'"
            }
          }' \
          https://graph.microsoft.com/v1.0/users/$USER


          curl -X POST \
          --url https://api.sendgrid.com/v3/mail/send \
          -H "Authorization: Bearer $SENDGRID_API_KEY" \
          -H "Content-Type: application/json" \
          --data '{
            "personalizations": [
              {
                "to": [
                  {
                    "email": "'"$REPORTER"'",
                    "name": "John Doe"
                  }
                ],
                "subject": "Your Work Credentials"
              }
            ],
            "content": [
              {
                "type": "text/html",
                "value": "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\"> <html data-editor-version=\"2\" class=\"sg-campaigns\" xmlns=\"http://www.w3.org/1999/xhtml\"> <head> <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"> <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1\"> <!--[if !mso]><!--> <meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\"> <style type=\"text/css\"> body, p, div { font-family: arial,helvetica,sans-serif; font-size: 14px; } body { color: #000000; } body a { color: #1188E6; text-decoration: none; } p { margin: 0; padding: 0; } table.wrapper { width:100% !important; table-layout: fixed; -webkit-font-smoothing: antialiased; -webkit-text-size-adjust: 100%; -moz-text-size-adjust: 100%; -ms-text-size-adjust: 100%; } img.max-width { max-width: 100% !important; } .column.of-2 { width: 50%; } .column.of-3 { width: 33.333%; } .column.of-4 { width: 25%; } ul ul ul ul { list-style-type: disc !important; } ol ol { list-style-type: lower-roman !important; } ol ol ol { list-style-type: lower-latin !important; } ol ol ol ol { list-style-type: decimal !important; } @media screen and (max-width:480px) { .preheader .rightColumnContent, .footer .rightColumnContent { text-align: left !important; } .preheader .rightColumnContent div, .preheader .rightColumnContent span, .footer .rightColumnContent div, .footer .rightColumnContent span { text-align: left !important; } .preheader .rightColumnContent, .preheader .leftColumnContent { font-size: 80% !important; padding: 5px 0; } table.wrapper-mobile { width: 100% !important; table-layout: fixed; } img.max-width { height: auto !important; max-width: 100% !important; } a.bulletproof-button { display: block !important; width: auto !important; font-size: 80%; padding-left: 0 !important; padding-right: 0 !important; } .columns { width: 100% !important; } .column { display: block !important; width: 100% !important; padding-left: 0 !important; padding-right: 0 !important; margin-left: 0 !important; margin-right: 0 !important; } .social-icon-column { display: inline-block !important; } } </style> <!--user entered Head Start--><!--End Head user entered--> </head> <body> <center class=\"wrapper\" data-link-color=\"#1188E6\" data-body-style=\"font-size:14px; font-family:arial,helvetica,sans-serif; color:#000000; background-color:#FFFFFF;\"> <div class=\"webkit\"> <table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" width=\"100%\" class=\"wrapper\" bgcolor=\"#FFFFFF\"> <tr> <td valign=\"top\" bgcolor=\"#FFFFFF\" width=\"100%\"> <table width=\"100%\" role=\"content-container\" class=\"outer\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"> <tr> <td width=\"100%\"> <table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"> <tr> <td> <!--[if mso]> <center> <table><tr><td width=\"600\"> <![endif]--> <table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:100%; max-width:600px;\" align=\"center\"> <tr> <td role=\"modules-container\" style=\"padding:0px 0px 0px 0px; color:#000000; text-align:left;\" bgcolor=\"#FFFFFF\" width=\"100%\" align=\"left\"> <table class=\"module preheader preheader-hide\" role=\"module\" data-type=\"preheader\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"display: none !important; mso-hide: all; visibility: hidden; opacity: 0; color: transparent; height: 0; width: 0;\"> <tr> <td role=\"module-content\"> <p></p> </td> </tr> </table> <table class=\"wrapper\" role=\"module\" data-type=\"image\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"table-layout: fixed;\" data-muid=\"4bddb8b6-07a7-4b42-87a5-1910d4f7cb25\"> <tbody> <tr> <td style=\"font-size:6px; line-height:10px; padding:0px 0px 0px 0px;\" valign=\"top\" align=\"left\"> <a href=\"https://www.arteria.ai/\"><img class=\"max-width\" border=\"0\" style=\"display:block; color:#000000; text-decoration:none; font-family:Helvetica, arial, sans-serif; font-size:16px; max-width:30% !important; width:30%; height:auto !important;\" width=\"180\" alt=\"Arteria AI\" data-proportionally-constrained=\"true\" data-responsive=\"true\" src=\"http://cdn.mcauto-images-production.sendgrid.net/7989cfc2524ac7c5/2c03101c-69dd-4ee7-b5ca-6c664b199534/4320x2430.png\"></a></td> </tr> </tbody> </table> <table class=\"module\" role=\"module\" data-type=\"divider\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"table-layout: fixed;\" data-muid=\"07d7808a-1f60-4454-b46f-53579522abca\"> <tbody> <tr> <td style=\"padding:0px 0px 0px 0px;\" role=\"module-content\" height=\"100%\" valign=\"top\" bgcolor=\"\"> <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" width=\"100%\" height=\"1px\" style=\"line-height:1px; font-size:1px;\"> <tbody> <tr> <td style=\"padding:0px 0px 1px 0px;\" bgcolor=\"#b5abab\"></td> </tr> </tbody> </table> </td> </tr> </tbody> </table> <table class=\"module\" role=\"module\" data-type=\"text\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"table-layout: fixed;\" data-muid=\"efcdb915-3143-4348-918d-b90c9b355f82\" data-mc-module-version=\"2019-10-22\"> <tbody> <tr> <td style=\"padding:18px 0px 18px 0px; line-height:22px; text-align:inherit;\" height=\"100%\" valign=\"top\" bgcolor=\"\" role=\"module-content\"><div><div style=\"font-family: inherit; text-align: inherit\">Hi John!</div> <div style=\"font-family: inherit; text-align: inherit\"><br></div> <div style=\"font-family: inherit; text-align: inherit\">Welcome to your first day. Below, you\'ll find your Arteria login credentials for accessing company resources. Should you have any questions or encounter any issues, please don\'t hesitate to respond to this email.</div> <div style=\"font-family: inherit; text-align: inherit\"><br></div> <div style=\"font-family: inherit; text-align: inherit\"><strong>Login Credentials</strong></div> <div style=\"font-family: inherit; text-align: inherit\"><br></div> <div style=\"font-family: inherit; text-align: inherit\"><strong>Email Address:&nbsp;</strong></div> <div style=\"font-family: inherit; text-align: inherit\"><strong>Password:&nbsp;</strong></div> <div style=\"font-family: inherit; text-align: inherit\"><br></div> <div style=\"font-family: inherit; text-align: inherit\">Regards,</div> <div style=\"font-family: inherit; text-align: inherit\">Arteria Service Desk</div><div></div></div></td> </tr> </tbody> </table> <div data-role=\"module-unsubscribe\" class=\"module\" role=\"module\" data-type=\"unsubscribe\" style=\"color:#444444; font-size:12px; line-height:20px; padding:16px 16px 16px 16px; text-align:Center;\" data-muid=\"4e838cf3-9892-4a6d-94d6-170e474d21e5\"><div class=\"Unsubscribe--addressLine\"></div><p style=\"font-size:12px; line-height:20px;\"><a target=\"_blank\" class=\"Unsubscribe--unsubscribeLink zzzzzzz\" href=\"{{{unsubscribe}}}\" style=\"\">Unsubscribe</a> - <a href=\"{{{unsubscribe_preferences}}}\" target=\"_blank\" class=\"Unsubscribe--unsubscribePreferences\" style=\"\">Unsubscribe Preferences</a></p></div></td> </tr> </table> </td> </tr> </table> </td> </tr> </table> </td> </tr> </table> </div> </center> </body> </html>"
              }
            ],
            "from": {
              "email": "admin@kencamarador.com",
              "name": "Service Desk"
            },
            "reply_to": {
              "email": "admin@kencamarador.com",
              "name": "Service Desk"
            }
          }'



